### PR TITLE
Feature/show leafs 2

### PR DESCRIPTION
**Pull request by tjomson**
# How was this tested?
Didn't make any tests, i'm tired 😫

# Type of change

Please check all boxes that apply to this change below.

| Type                     | Applies ✅|
| ------------------------ | :-------: |
| Backend                  |    ✅       |
| Frontend                 |     ✅      |
| Github/Ci/Admin          |           |
| Documentation required   |           |

# Checklist

Please follow the checklist below and check all completed items as you work on the PR.

I have..
- [x] performed a self-review of my own code
- [x] commented my code, particularly in hard-to-understand areas
- [ ] written documentation
- [ ] added automated tests
- [ ] merged dependencies to `develop

### CODE REVIEW

**Review by hojelse — CHANGES_REQUESTED** [review]
This unit test fails: `backend.Tests.DrawablesProcessorTests.ProcessLinksTest`

```
Error Message:
   System.ArgumentNullException : Value cannot be null. (Parameter 'key')
  Stack Trace:
     at System.Collections.Generic.Dictionary`2.FindValue(TKey key)
   at System.Collections.Generic.Dictionary`2.ContainsKey(TKey key)
   at backend.DrawablesProcessor.ProcessLeafs() in /home/runner/work/nats-topology-visualiser/nats-topology-visualiser/backend/DrawablesProcessor.cs:line 79
   at backend.DrawablesProcessor.ProcessData() in /home/runner/work/nats-topology-visualiser/nats-topology-visualiser/backend/DrawablesProcessor.cs:line 32
   at backend.DrawablesProcessor..ctor(DataStorage dataStorage) in /home/runner/work/nats-topology-visualiser/nats-topology-visualiser/backend/DrawablesProcessor.cs:line 17
```

**Review by hojelse — DISMISSED** [review]
Works great! Does lack unit tests though.

**Review by hojelse — DISMISSED** [review]
Look very good!

Nice long links :)

**Review by KirstineBerg — DISMISSED** [review]
With my limited knowledge of exactly what you're doing, I think it looks good!

**Review by TKShade — APPROVED** [review]
looks good

**Review by hojelse — APPROVED** [review]
Gogogo! 🚀

**Pull request merged**
