### PR TITLE
Release 0.2.0

### PR DESCRIPTION
**Pull request by hojelse**

### CODE REVIEW

**Review by tjomson — APPROVED** [review]
Yay release time

**Comment by tjomson** [comment]
There is an error in Chrome where it does not think that processedServers can be iterated over. It seems like this is not a problem in firefox, and it also seems like moving the logic to the backend fixes the problem.

**Comment by tjomson** [comment]
There is an error where Chrome does not think that processedServers can be iteratied over. It appears that this is not a problem in Firefox, and it also seems like moving the logic to the backend fixes the problem.

**Review by pizzaluc — APPROVED** [review]
Looks great! Dont have anything to add atm

**Pull request merged**
