### PR TITLE
Reset button for search bar

### PR DESCRIPTION
**Pull request by SmillaDion**
# How was this tested?

It's frontend only, so... by looking with my eyes?

# Type of change

Please check all boxes that apply to this change below.

| Type                     | Applies ✅|
| ------------------------ | :-------: |
| Backend                  |           |
| Frontend                 |     ✅     |
| Github/Ci/Admin          |           |
| Documentation required   |           |

# Checklist

Please follow the checklist below and check all completed items as you work on the PR.

I have..
- [x] performed a self-review of my own code
- [x] commented my code, particularly in hard-to-understand areas
- [ ] written documentation
- [ ] added automated tests
- [ ] merged dependencies to `develop

### CODE REVIEW

**Review by Maasdamind — DISMISSED** [review]
Looks great! 👍

**Review by Maasdamind — APPROVED** [review]
Looks great 2: electric Boogaloo

**Comment by tjomson** [comment]
Can we add TS to SearchBar? 🥺

**Review by Maasdamind — APPROVED** [review]
Looks amazing! Great job 🚀 🤖

**Pull request merged**
