### PR TITLE
feat(Docker): add dockerfile and dockerfile creation workflow

### PR DESCRIPTION
**Pull request by Maasdamind**
# How was this tested?

* Step one etc.

# Type of change

Please check all boxes that apply to this change below.

| Type                     | Applies ✅|
| ------------------------ | :-------: |
| Backend                  |     ✅   |
| Frontend                 |           |
| Github/Ci/Admin          |   ✅    |
| Documentation required   |           |

# Checklist

Please follow the checklist below and check all completed items as you work on the PR.

I have..
- [x] performed a self-review of my own code
- [ ] commented my code, particularly in hard-to-understand areas
- [ ] written documentation
- [x] added automated tests
- [ ] merged dependencies to `develop

### CODE REVIEW

**Review by TKShade — DISMISSED** [review]
Looks ok

**Review by TKShade — DISMISSED** [review]
regarding backend/Startup.cs:
line 41: maybe we should replace * with something specific as David warned us of this.

**Review by tjomson — APPROVED** [review]
YAAAAASSSSS

**Review by hojelse — APPROVED** [review]
🚀

**Review by EDBM — APPROVED** [review]

**Pull request merged**
