### PR TITLE
Testing/Code Coverage

### PR DESCRIPTION
**Pull request by Maasdamind**
#se include a summary of the change and which issue it fixes. Please also include relevant motivation and context. List any dependencies that are required for this change. -->

# How was this tested?

* Step one etc.

# Type of change

Please check all boxes that apply to this change below.

| Type                     | Applies ✅|
| ------------------------ | :-------: |
| Backend                  |           |
| Frontend                 |           |
| Github/Ci/Admin          |           |
| Documentation required   |           |

# Checklist

Please follow the checklist below and check all completed items as you work on the PR.

I have..
- [ ] performed a self-review of my own code
- [ ] commented my code, particularly in hard-to-understand areas
- [ ] written documentation
- [ ] added automated tests
- [ ] merged dependencies to `develop

### CODE REVIEW

**Comment by tjomson** [comment]
There are both a codecov.yaml and a codecov.yml, is this intentional?

**Comment by pizzaluc** [comment]
> There are both a codecov.yaml and a codecov.yml, is this intentional?

My bad, the .yaml need to be deleted

**Review by hojelse — APPROVED** [review]
Don't know how to test if this works. But reading through it, clarity of the code is great.

**Comment by pizzaluc** [comment]
Duplicated files are removed now, i hope the reports will make more sense when more reports have been generated, but not entirely sure

**Comment by Maasdamind** [comment]
> Don't know how to test if this works. I see codecov has commented on #40 but looks like develop need to have a report before the output is meaningful?

Yes exactly. We should get this merged asap. Can we get another review and stamp of approval @hojelse ? 🚀

**Review by pizzaluc — APPROVED** [review]
Really nice and clean code, must be a god at BDSA

**Review by hojelse — APPROVED** [review]

**Comment by hojelse** [comment]
> > Don't know how to test if this works. I see codecov has commented on #40 but looks like develop need to have a report before the output is meaningful?
> 
> Yes exactly. We should get this merged asap. Can we get another review and stamp of approval @hojelse ? 🚀

Sorry didn't see your @ ❤️

**Pull request merged**
