### PR TITLE
Refactor(backend): move solution to root and refactor folders

### PR DESCRIPTION
**Pull request by Maasdamind**

### CODE REVIEW

**Comment by pizzaluc** [comment]
Added small commit to fix the path and we still cant do `dotnet run` in the root folder. We need to create a `Makefile` or perhaps something like this in the package.json 

`"start": "dotnet run -p backend/backend.csproj & vue-cli-service serve"`

**Comment by tjomson** [comment]
I am getting an error when trying to dotnet run about duplicate attributes in some file in the obj folder.
Do we need even need the folders "backend" and "backend.tests" when they only contain bin and obj folders?

**Comment by Maasdamind** [comment]
> I am getting an error when trying to dotnet run about duplicate attributes in some file in the obj folder.
> Do we need even need the folders "backend" and "backend.tests" when they only contain bin and obj folders?

Oh yeah these should be deleted. They must've not have been removed since they are added to .Gitignore

**Comment by tjomson** [comment]
> Oh yeah these should be deleted. They must've not have been removed since they are added to .Gitignore

Ahh, i think it was my local files that were messed up.

**Review by tjomson — DISMISSED** [review]
Nice refactor 👍 We could consider removing unnecessary entries in gitignore, but it is no big deal. I am thinking about these: 
backend/backend/bin/*
backend/backend/obj/

**Comment by hojelse** [comment]
Got the same error as tjomson, updated gitignore such that any bin and obj anywhere in the project will be ignored

**Review by hojelse — APPROVED** [review]
Works locally on my machine, so looks good to me 🚀

**Pull request merged**
